services:
  - type: worker
    name: txt-uploader-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 handlers/ytc.py"
    envVars:
      - key: BOT_TOKEN
        sync: false